services:
    
    ################################################################################
    # SPLASH Open Api Connector Service
    splash.connectors.openapi:
        class:      Splash\OpenApi\Bundle\Services\OpenApiConnector
        autowire:   true
        calls:
            - setMetaDir:   ["%kernel.cache_dir%"]
            - setValidator: ["@validator"]
        tags:
            - { name: "splash.connector" }
