
splash:
    # Allow Notifications for Generic Users
    notify: ["ROLE_USER"]
    
    ################################################################################
    # List of Available Connector Connections
    ################################################################################
    connections:
        
        ########################################################################
        # Open Api SandBox
        sandbox:
            id:                 ThisIsSandBoxWsId
            key:                ThisIsNotASecretKeyForSandBox
            name:               Open API Sandbox
            connector:          openapi
            ########################################################################
            # FAKE CREDENTIALS : ASK YOURS TO YOUR MAIN RECOMMERCE CONTACT
            ########################################################################
            config:
                WsHost:         http://openapi
                ApiKey:         ThisIsSecretApiKey
